export const categories = [
    {
        companyName: "Foodmandu",
        companyService: "Food Delivery Service",
        image: "image-13.png",
        location: "Kathmandu, Nepal",
        totalJobs: "33+ jobs",
        title: "Senior Graphic Designer",
        type: "Fulltime",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
        nrs: 25000,
        id: 1,

    },
    {
        companyName: "Foodmandu",
        companyService: "Food Delivery Service",
        image: "image-13.png",
        location: "Kathmandu, Nepal",
        totalJobs: "33+ jobs",
        title: "Frontend Developer",
        type: "Fulltime",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
        nrs: 25000,
        id: 2,

    },
    {
        companyName: "Foodmandu",
        companyService: "Food Delivery Service",
        image: "image-13.png",
        location: "Kathmandu, Nepal",
        totalJobs: "33+ jobs",
        title: "Frontend Developer",
        type: "Fulltime",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
        nrs: 25000,
        id: 3,

    },
    {
        companyName: "Foodmandu",
        companyService: "Food Delivery Service",
        image: "image-13.png",
        location: "Kathmandu, Nepal",
        totalJobs: "33+ jobs",
        title: "Frontend Developer",
        type: "Fulltime",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
        nrs: 25000,
        id: 4,

    },
    {
        companyName: "Foodmandu",
        companyService: "Food Delivery Service",
        image: "image-13.png",
        location: "Kathmandu, Nepal",
        totalJobs: "33+ jobs",
        title: "Frontend Developer",
        type: "Fulltime",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
        nrs: 25000,
        id: 5

    },
    {
        companyName: "Foodmandu",
        companyService: "Food Delivery Service",
        image: "image-13.png",
        location: "Kathmandu, Nepal",
        totalJobs: "33+ jobs",
        title: "Frontend Developer",
        type: "Fulltime",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
        nrs: 25000,
        id: 6,

    },
    {
        companyName: "Foodmandu",
        companyService: "Food Delivery Service",
        image: "image-13.png",
        location: "Kathmandu, Nepal",
        totalJobs: "33+ jobs",
        title: "Frontend Developer",
        type: "Fulltime",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
        nrs: 25000,
        id: 7,


    },
    {
        companyName: "Foodmandu",
        companyService: "Food Delivery Service",
        image: "image-13.png",
        location: "Kathmandu, Nepal",
        totalJobs: "33+ jobs",
        title: "Frontend Developer",
        type: "Fulltime",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
        nrs: 25000,
        id: 8

    },
    {
        companyName: "Foodmandu",
        companyService: "Food Delivery Service",
        image: "image-13.png",
        location: "Kathmandu, Nepal",
        totalJobs: "33+ jobs",
        title: "Frontend Developer",
        type: "Fulltime",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
        nrs: 25000,
        id: 9

    },
    {
        companyName: "Foodmandu",
        companyService: "Food Delivery Service",
        image: "image-13.png",
        location: "Kathmandu, Nepal",
        totalJobs: "33+ jobs",
        title: "Frontend Developer",
        type: "Fulltime",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
        nrs: 25000,
        id: 10,


    },
    {
        companyName: "Foodmandu",
        companyService: "Food Delivery Service",
        image: "image-13.png",
        location: "Kathmandu, Nepal",
        totalJobs: "33+ jobs",
        title: "Frontend Developer",
        type: "Fulltime",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
        nrs: 25000,
        id: 11,

    },
    {
        companyName: "Foodmandu",
        companyService: "Food Delivery Service",
        jobCategory: ": Engineering",
        jobLevel: ": Senior (2+ years)",
        jobType: ": Full time",
        offeredSalary: ": $500/month (negotiable)",
        deadline: ": 11th Sept, 2022",
        image: "image-13.png",
        location: "Kathmandu, Nepal",
        totalJobs: "33+ jobs",
        title: "Frontend Developer",
        type: "Fulltime",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consequat nunc ac a magna at elementum. Cras arcu varius in aliquam habitant fermentum. Mi sit lorem mollis vitae quis curabitur vestibulum.",
        nrs: 25000,
        id: 12,

    },

]